### ISSUE TITLE
npm install kafka-native --save fails on Ubuntu 16.04.

### ISSUE THREAD

**Issue by kuusemi** [jut-io/node-kafka-native#40]
Kernel version: 4.4.0-36-generic
npm -v: 3.7.5
node -v: v4.5.0

Install log:

  ACTION configuring librdkafka... deps/librdkafka/config.h
checking for OS or distribution... ok (Ubuntu)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for pkgconfig (by command)... ok
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... ok
parsing version '0x00080600'... ok (0.8.6)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for zlib (by pkg-config)... failed
checking for zlib (by compile)... failed (fail)
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for nm (by env NM)... ok (cached)
checking for perl (by command)... ok
###### 
###### 
###### 

 zlib () 
    module: librdkafka
    action: fail
    reason:
compile check failed:
CC: CC
flags: -lz
gcc  -g -O2 -fPIC -Wall -Werror -Wfloat-equal -Wpointer-arith -Wall -Werror -lz _mkltmppu0VD.c -o _mkltmppu0VD.c.o  :
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
source: 

librdkafka_config_h.target.mk:13: recipe for target 'deps/librdkafka/config.h' failed
make: **\* [deps/librdkafka/config.h] Error 1

**Comment by edenhill** [comment]
librdkafka 0.8.6 requires, try: `sudo apt-get install zlib1g-dev`.

You should also consider upgrading to librdkafka 0.9.1 or master, 0.8.6 is old.

**Comment by kuusemi** [comment]
Thanks for the quick reply. Alter installing the zlib1g-dev package, I was able to install kafka-native module. This ticket can be closed.

I'll also concider upgrading to the newer version of librdkafka.
